language: php

php:
- 7.1
- 7.2
- 7.3

sudo: required

services:
- docker

before_install:
- docker pull edamov/pushok-docker

script:
- docker run --name=php7.1 -e TRAVIS=true -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}" -d -v /home/travis/build/edamov/pushok:/home/pushok edamov/pushok-docker tail -f /dev/null
- docker exec -t php7.1 /bin/sh -c "cd /home/pushok && php /composer.phar update ${COMPOSER_FLAGS} --no-interaction --prefer-dist && /home/pushok/vendor/bin/phpunit --coverage-clover /home/pushok/build/logs/clover.xml && php /home/pushok/vendor/bin/php-coveralls -v"
